{% set name = "pydrobert-kaldi" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydrobert-kaldi-{{ version }}.tar.gz
  sha256: d44aefb58c96141ef705f7cb4fc692c15f348bb2fdef2a1f275589062c83c66a

build:
  skip: true  # [py<37]
  entry_points:
    - write-table-to-pickle = pydrobert.kaldi.command_line:write_table_to_pickle
    - write-pickle-to-table = pydrobert.kaldi.command_line:write_pickle_to_table
    - compute-error-rate = pydrobert.kaldi.command_line:compute_error_rate
    - normalize-feat-lens = pydrobert.kaldi.command_line:normalize_feat_lens
    - write-table-to-torch-dir = pydrobert.kaldi.command_line:write_table_to_torch_dir
    - write-torch-dir-to-table = pydrobert.kaldi.command_line:write_torch_dir_to_table
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pip
    - python
    - setuptools >=45
    - setuptools_scm >=6.2
    - swig >=4.0.2
  run:
    - python
    - {{ pin_compatible('numpy') }}
  run_constrained:
    - pydrobert-param >0.2.0
    - pydrobert-pytorch >0.2.1
    - pydrobert-speech >0.1.0

test:
  imports:
    - pydrobert.kaldi
  commands:
    - pip check
    - write-table-to-pickle --help
    - write-pickle-to-table --help
    - compute-error-rate --help
    - normalize-feat-lens --help
    - write-table-to-torch-dir --help
    - write-torch-dir-to-table --help
  requires:
    - pip
    - pytorch

about:
  home: https://github.com/sdrobert/pydrobert-kaldi
  summary: Python wrapper for Kaldi
  license: Apache-2.0
  license_file:
    - LICENSE
    - COPYING_Kaldi_Project

extra:
  recipe-maintainers:
    - sdrobert