{% set name = "pydrobert-param" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydrobert-param-{{ version }}.tar.gz
  sha256: 0fbf38924b1543e824c52821a65334e7fa60e560474e98558ef2ca36d75dc56d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - combine-ini-files = pydrobert.param.command_line:combine_ini_files
    - combine-json-files = pydrobert.param.command_line:combine_json_files
    - combine-yaml-files = pydrobert.param.command_line:combine_yaml_files

requirements:
  host:
    - pip
    - setuptools >=45
    - setuptools_scm >=6.2
    - python >=3.7
  run:
    - param >=1.9
    - python >=3.7

test:
  imports:
    - pydrobert.param
  commands:
    - pip check
    - combine-ini-files --help
    - combine-json-files --help
    - combine-yaml-files --help
  requires:
    - pip
    - pyyaml

about:
  home: https://github.com/sdrobert/pydrobert-param
  summary: Utilities for the python package 'param'
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sdrobert
